
name: build-node-ci


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: All Run
        run:  |
          npm install
          npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}
          path: dist/
          retention-days: 14
        
        
  deploy:
      name: 'Dummy deploy'
      needs: build
      runs-on: ubuntu-latest
      environment: 
        name: DEV
        url: 'https://example.com'

      steps:
        - name: 'Descarga artifact'
          uses: actions/download-artifact@v4
          with:
            name: ${{ github.run_id }}

        - name: 'Imprimir variables de entorno'
          run: |
            echo "Variables de entorno: ${{secrets.DEV_SECRET}}"
            echo "Variables de entorno: ${{vars.DEV_VAR}}"
